export const MARKETS = [
  {
    slug: "spokane",
    name: "Spokane",
    state: "WA",
    tagline: "Valley, Liberty Lake, Cheney, and nearby towns",
    dataforseoLocation: "Spokane,Washington,United States",
    licenseEnrichment: "wa" as const,
    live: true,
    cityAliases: [
      "Spokane",
      "Spokane Valley",
      "Liberty Lake",
      "Airway Heights",
      "Cheney",
      "Medical Lake",
      "Deer Park",
      "Millwood",
      "Mead",
      "Otis Orchards",
      "Greenacres",
      "Veradale",
      "Nine Mile Falls",
      "Colbert",
      "Chattaroy",
      "Fairchild AFB",
      "Spangle",
      "Marshall",
      "Town and Country",
      "Country Homes",
      "South Hill",
      "Coeur d'Alene",
      "Post Falls",
    ],
  },
  {
    slug: "boise",
    name: "Boise",
    state: "ID",
    tagline: "Meridian, Eagle, Nampa, and the Treasure Valley",
    dataforseoLocation: "Boise,Idaho,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Boise",
      "Meridian",
      "Eagle",
      "Nampa",
      "Garden City",
      "Kuna",
      "Star",
    ],
  },
  {
    slug: "raleigh",
    name: "Raleigh",
    state: "NC",
    tagline: "Cary, Durham, Apex, and Wake County towns",
    dataforseoLocation: "Raleigh,North Carolina,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Raleigh",
      "Cary",
      "Apex",
      "Fuquay-Varina",
      "Garner",
      "Wake Forest",
      "Holly Springs",
      "Durham",
    ],
  },
  {
    slug: "portland",
    name: "Portland",
    state: "OR",
    tagline: "Beaverton, Hillsboro, Gresham, and Vancouver WA",
    dataforseoLocation: "Portland,Oregon,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Portland",
      "Beaverton",
      "Hillsboro",
      "Tigard",
      "Lake Oswego",
      "Gresham",
      "Vancouver",
    ],
  },
  {
    slug: "indianapolis",
    name: "Indianapolis",
    state: "IN",
    tagline: "Carmel, Fishers, Noblesville, and nearby towns",
    dataforseoLocation: "Indianapolis,Indiana,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Indianapolis",
      "Carmel",
      "Fishers",
      "Noblesville",
      "Greenwood",
      "Westfield",
      "Zionsville",
    ],
  },
  {
    slug: "kansas-city",
    name: "Kansas City",
    state: "KS/MO",
    tagline: "Overland Park, Olathe, Lenexa, and Johnson County",
    dataforseoLocation: "Kansas City,Missouri,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Kansas City",
      "Overland Park",
      "Lenexa",
      "Olathe",
      "Lee's Summit",
      "Shawnee",
    ],
  },
  {
    slug: "nashville",
    name: "Nashville",
    state: "TN",
    tagline: "Franklin, Murfreesboro, Brentwood, and nearby towns",
    dataforseoLocation: "Nashville,Tennessee,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Nashville",
      "Franklin",
      "Murfreesboro",
      "Brentwood",
      "Hendersonville",
      "Gallatin",
      "Smyrna",
    ],
  },
  {
    slug: "charlotte",
    name: "Charlotte",
    state: "NC",
    tagline: "Concord, Huntersville, Matthews, and Rock Hill",
    dataforseoLocation: "Charlotte,North Carolina,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Charlotte",
      "Concord",
      "Mooresville",
      "Cornelius",
      "Matthews",
      "Huntersville",
      "Rock Hill",
    ],
  },
  {
    slug: "salt-lake",
    name: "Salt Lake Valley",
    state: "UT",
    tagline: "Sandy, South Jordan, Draper, and nearby towns",
    dataforseoLocation: "Salt Lake City,Utah,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Salt Lake City",
      "Sandy",
      "South Jordan",
      "West Jordan",
      "Draper",
      "Lehi",
      "Midvale",
    ],
  },
  {
    slug: "columbus",
    name: "Columbus",
    state: "OH",
    tagline: "Westerville, Dublin, Hilliard, and nearby towns",
    dataforseoLocation: "Columbus,Ohio,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Columbus",
      "Westerville",
      "Dublin",
      "Hilliard",
      "Worthington",
    ],
  },
  {
    slug: "denver",
    name: "Denver",
    state: "CO",
    tagline: "Littleton, Castle Rock, Parker, and nearby suburbs",
    dataforseoLocation: "Denver,Colorado,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Denver",
      "Littleton",
      "Castle Rock",
      "Parker",
      "Arvada",
      "Centennial",
      "Englewood",
      "Westminster",
    ],
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    state: "AZ",
    tagline: "Gilbert, Chandler, Mesa, and the East Valley",
    dataforseoLocation: "Phoenix,Arizona,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Phoenix",
      "Gilbert",
      "Chandler",
      "Mesa",
      "Peoria",
      "Surprise",
      "Queen Creek",
    ],
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    state: "GA",
    tagline: "Marietta, Alpharetta, Roswell, and North Atlanta towns",
    dataforseoLocation: "Atlanta,Georgia,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Atlanta",
      "Marietta",
      "Alpharetta",
      "Roswell",
      "Woodstock",
      "Kennesaw",
      "Lawrenceville",
    ],
  },
  {
    slug: "northern-virginia",
    name: "Northern Virginia",
    state: "VA",
    tagline: "Ashburn, Leesburg, Fairfax, and nearby towns",
    dataforseoLocation: "Fairfax,Virginia,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Sterling",
      "Ashburn",
      "Leesburg",
      "Fairfax",
      "Manassas",
      "Woodbridge",
      "Reston",
    ],
  },
  {
    slug: "minneapolis",
    name: "Minneapolis",
    state: "MN",
    tagline: "Plymouth, Maple Grove, Eden Prairie, and nearby towns",
    dataforseoLocation: "Minneapolis,Minnesota,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Minneapolis",
      "Plymouth",
      "Maple Grove",
      "Eden Prairie",
      "Woodbury",
      "Bloomington",
    ],
  },
  {
    slug: "milwaukee",
    name: "Milwaukee",
    state: "WI",
    tagline: "Waukesha, Brookfield, Wauwatosa, and nearby towns",
    dataforseoLocation: "Milwaukee,Wisconsin,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Milwaukee",
      "Waukesha",
      "Brookfield",
      "New Berlin",
      "West Allis",
      "Wauwatosa",
    ],
  },
  {
    slug: "huntsville",
    name: "Huntsville",
    state: "AL",
    tagline: "Madison and nearby towns",
    dataforseoLocation: "Huntsville,Alabama,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: ["Huntsville", "Madison"],
  },
  {
    slug: "richmond",
    name: "Richmond",
    state: "VA",
    tagline: "Midlothian, Glen Allen, and Henrico",
    dataforseoLocation: "Richmond,Virginia,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Richmond",
      "Midlothian",
      "Mechanicsville",
      "Glen Allen",
      "Henrico",
    ],
  },
  {
    slug: "charleston",
    name: "Charleston",
    state: "SC",
    tagline: "Mount Pleasant, North Charleston, and Summerville",
    dataforseoLocation: "Charleston,South Carolina,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Charleston",
      "Mount Pleasant",
      "North Charleston",
      "Summerville",
    ],
  },
  {
    slug: "omaha",
    name: "Omaha",
    state: "NE",
    tagline: "Omaha and nearby towns",
    dataforseoLocation: "Omaha,Nebraska,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: ["Omaha"],
  },
  {
    slug: "oklahoma-city",
    name: "Oklahoma City",
    state: "OK",
    tagline: "Edmond and Oklahoma City",
    dataforseoLocation: "Oklahoma City,Oklahoma,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: ["Oklahoma City", "Edmond"],
  },
  {
    slug: "birmingham",
    name: "Birmingham",
    state: "AL",
    tagline: "Hoover and nearby suburbs",
    dataforseoLocation: "Birmingham,Alabama,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: ["Birmingham", "Hoover"],
  },
  {
    slug: "greenville",
    name: "Greenville",
    state: "SC",
    tagline: "Simpsonville and nearby towns",
    dataforseoLocation: "Greenville,South Carolina,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: ["Greenville", "Simpsonville"],
  },
  {
    slug: "des-moines",
    name: "Des Moines",
    state: "IA",
    tagline: "Des Moines and Ankeny",
    dataforseoLocation: "Des Moines,Iowa,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: ["Des Moines", "Ankeny"],
  },
  {
    slug: "seattle",
    name: "Seattle",
    state: "WA",
    tagline: "Everett, Puyallup, Kirkland, and the Puget Sound ring",
    dataforseoLocation: "Seattle,Washington,United States",
    licenseEnrichment: false as const,
    live: true,
    cityAliases: [
      "Seattle",
      "Everett",
      "Puyallup",
      "Snohomish",
      "Lake Stevens",
      "Marysville",
      "Kirkland",
    ],
  },
] as const;

export type Market = (typeof MARKETS)[number];
export type MarketSlug = Market["slug"];

export const DEFAULT_MARKET_SLUG: MarketSlug = "spokane";

export const DIRECTORY_MARKET_SLUGS = MARKETS.map((market) => market.slug);

export function isMarketSlug(value: string): value is MarketSlug {
  return MARKETS.some((market) => market.slug === value);
}

export function getMarket(slug: string): Market | undefined {
  return MARKETS.find((market) => market.slug === slug);
}

export function requireMarket(slug: string): Market {
  const market = getMarket(slug);
  if (!market) {
    throw new Error(`Unknown market: ${slug}`);
  }
  return market;
}

export function liveMarkets(): Market[] {
  return MARKETS.filter((market) => market.live);
}

export function marketCoreCities(slug: string): Set<string> {
  const market = getMarket(slug);
  return new Set(
    (market?.cityAliases ?? []).map((city) => city.replace(/\s+/g, " ").trim().toLowerCase()),
  );
}
